---
- hosts: piholes, general_servers
  vars_files:
    - '../vars/vars.yml'
  become: yes
  tasks:
    - name: Change user password
      user:
        name: serveradmin
        update_password: always
        password: "{{ newpassword|password_hash('sha512')  }}"
